apiVersion: batch/v1
kind: Job
metadata:
  name: loadgenerator-job
spec:
  template:
    spec:
      containers:
      - name: loadgenerator
        image: ghcr.io/michaeltrip/loadgenerator:latest
        args: ["--max-cpu 50 --max-memory 512 --target-ip iperf3test.iperf --port 5301"]
      restartPolicy: Never
  backoffLimit: 4

